#:schema node_modules/wrangler/config-schema.json
name = "brainstormer"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "TRENDS"
id = "609b8808e46a49198264759ea76b3155"
